#Importing and Linking all the HDL source files used in the design
import_files -library work -hdl_source hdl/CameraIO_ip_addr_decoder.v
import_files -library work -hdl_source hdl/CameraIO_ip_SimpleDualPortRAM_generic.v
import_files -library work -hdl_source hdl/CameraIO_ip_rdfifo_data.v
import_files -library work -hdl_source hdl/CameraIO_ip_SimpleDualPortRAM_singlebit.v
import_files -library work -hdl_source hdl/CameraIO_ip_rdfifo_last.v
import_files -library work -hdl_source hdl/CameraIO_ip_rdfifo_rid.v
import_files -library work -hdl_source hdl/CameraIO_ip_axi4_module.v
import_files -library work -hdl_source hdl/CameraIO_ip_axi4.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_RADAR0_i2c_slave.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_RADAR0_MIPI_I2C.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_RADAR0_i2c_slave_block.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_RADAR1_MIPI_I2C.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_i2c_slave_serializer.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_Chart.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_sclDeb.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_sdaDeb.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_TCA6424A.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_i2c_slave_serializer_block.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_pulse.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_sco_slave_sel.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_sdo_master_sel.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_TCA9548A.v
import_files -library work -hdl_source hdl/CameraIO_ip_src_CameraIO.v
import_files -library work -hdl_source hdl/CameraIO_ip_dut.v
import_files -library work -hdl_source hdl/CameraIO_ip_reset_sync.v
import_files -library work -hdl_source hdl/CameraIO_ip.v
import_files -library work -hdl_source hdl/SYSTEM_ip_SimpleDualPortRAM_generic.v
import_files -library work -hdl_source hdl/SYSTEM_ip_rd_addr_fifo.v
import_files -library work -hdl_source hdl/SYSTEM_ip_rd_len_fifo.v
import_files -library work -hdl_source hdl/SYSTEM_ip_rdata_fifo.v
import_files -library work -hdl_source hdl/SYSTEM_ip_axi4_master_rd.v
import_files -library work -hdl_source hdl/SYSTEM_ip_wdata_fifo.v
import_files -library work -hdl_source hdl/SYSTEM_ip_SimpleDualPortRAM_singlebit.v
import_files -library work -hdl_source hdl/SYSTEM_ip_wlast_fifo.v
import_files -library work -hdl_source hdl/SYSTEM_ip_wr_addr_fifo.v
import_files -library work -hdl_source hdl/SYSTEM_ip_wr_data_fifo.v
import_files -library work -hdl_source hdl/SYSTEM_ip_wr_len_fifo.v
import_files -library work -hdl_source hdl/SYSTEM_ip_axi4_master_wr.v
import_files -library work -hdl_source hdl/SYSTEM_ip_addr_decoder.v
import_files -library work -hdl_source hdl/SYSTEM_ip_rdfifo_data.v
import_files -library work -hdl_source hdl/SYSTEM_ip_rdfifo_last.v
import_files -library work -hdl_source hdl/SYSTEM_ip_rdfifo_rid.v
import_files -library work -hdl_source hdl/SYSTEM_ip_reset_hold.v
import_files -library work -hdl_source hdl/SYSTEM_ip_axi4_module.v
import_files -library work -hdl_source hdl/SYSTEM_ip_axi4.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_SimpleDualPortRAM_generic.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_HDL_FIFO.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_init.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_Compare_To_Constant.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_proc.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_spi_sm.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_AD7173_8_ADC_0.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_AD7173_8_Proc_0.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_HDL_FIFO_block.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_init_block.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_pulse.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_spi_sm_block.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_AD9545CC.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_spi_slave.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_SPISlave.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_acc0.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_acc1.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_acc2.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_acc3.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_Temperature_and_Voltage_Sensor.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_AXI4LiteMaster.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_spi_slave_block.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_spi2axil.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_Pulse_extender_ctrl.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_pulse_10mks1.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_pulse_10mks.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_time_stamp_engine.v
import_files -library work -hdl_source hdl/SYSTEM_ip_src_SYSTEM.v
import_files -library work -hdl_source hdl/SYSTEM_ip_dut.v
import_files -library work -hdl_source hdl/SYSTEM_ip_reset_sync.v
import_files -library work -hdl_source hdl/SYSTEM_ip.v
